[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gamenet"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
rcgen = { workspace = true }
bytes = { workspace = true }
gamenet-core = { path = "../core" }
rpassword = "7.5"

[dev-dependencies]
tempfile = "3"
