[package]
name = "gamenet-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
tokio = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
rcgen = { workspace = true }
bytes = { workspace = true }
getrandom = "0.2"
webpki-roots = "1"
tempfile = "3"
ring = "0.17"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_System_Threading"] }
